In [ ]:
Q1.Create a null vector of size 10 but the fifth value which is 1.

In [9]:
import numpy as np

null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
Q2.Create a vector with values ranging from 10 to 49.

In [8]:
import numpy as np

vector = np.arange(10, 50)
print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
Q3.Create a 3x3 matrix with values ranging from 0 to 8

In [17]:
import numpy as np

values = np.arange(9)
matrix = values.reshape(3, 3)
print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
Q4.Find indices of non-zero elements from [1,2,0,0,4,0]

In [20]:
import numpy as np


arr = np.array([1, 2, 0, 0, 4, 0])
nonzero_indices = np.nonzero(arr)
print(nonzero_indices)


(array([0, 1, 4], dtype=int64),)


In [ ]:
Q5. Create a 10x10 array with random values and find the minimum and maximum values.

In [30]:
import numpy as np

array = np.random.rand(10, 10)
min_value = np.min(array)
max_value = np.max(array)
print("Array:")
print(array)
print(f"Minimum value: {min_value}")
print(f"Maximum value: {max_value}")


Array:
[[8.12220334e-01 7.57699841e-02 9.56010430e-01 7.44968161e-01
  1.91680258e-01 2.49349719e-01 7.40662442e-01 2.43032152e-01
  4.02738449e-01 9.57033626e-01]
 [8.48852292e-01 3.61425645e-01 8.48418076e-01 1.00977017e-01
  4.79208937e-01 4.34069703e-01 2.98100704e-01 6.03584308e-01
  4.22330492e-04 5.21587817e-01]
 [1.28794010e-02 7.96929648e-01 8.55234807e-01 6.64470668e-01
  9.00393496e-02 1.61232862e-01 7.30804464e-01 3.05103089e-01
  6.77896754e-01 8.61980637e-01]
 [3.77119962e-01 8.11491878e-01 6.98635837e-01 5.96799547e-01
  6.99930848e-01 8.80002892e-01 7.09153168e-02 9.89262387e-01
  3.19087714e-01 4.03866957e-01]
 [2.69711623e-01 9.22680601e-01 4.02721942e-02 1.52620054e-01
  9.09559901e-01 5.58365463e-01 4.83217679e-01 7.23622694e-01
  1.12399476e-01 1.56056457e-01]
 [8.39671307e-01 8.51592242e-01 3.63784191e-01 6.49487224e-01
  4.50112927e-01 2.66186775e-01 9.33643244e-01 3.20593962e-01
  3.81172013e-01 9.63521061e-01]
 [4.72704543e-03 2.83229850e-02 2.64918978e-01 2.70

In [ ]:
Q6. Create a random vector of size 30 and find the mean value.

In [38]:
import numpy as np

vector = np.random.rand(30)
mean_value = np.mean(vector)
print("Random Vector:")
print(vector)
print(f"Mean value: {mean_value}")


Random Vector:
[0.17429963 0.53054057 0.23611648 0.84184546 0.72934448 0.97066732
 0.08847736 0.91690497 0.13452248 0.92962134 0.14285468 0.39403344
 0.71063072 0.00960468 0.192196   0.22662091 0.31679875 0.90588441
 0.25862445 0.08030997 0.39746024 0.55491057 0.82062928 0.41351108
 0.35718553 0.98586806 0.71776027 0.48538595 0.61783089 0.82625696]
Mean value: 0.4988898971164794
